### PR TITLE
fix: updated make steps for more indivdual plan runs

### PR DESCRIPTION
**Pull request by baserrato**

### CODE REVIEW

**Review by snowmang1 — APPROVED** [review]
reviewed it when I pushed

**Comment by snowmang1** [comment]
This pr is not ready yet

**Review by snowmang1 — CHANGES_REQUESTED** [review]
add progress bar to Makefile

**Comment by baserrato** [comment]
@snowmang1 in your infinite wisdom, you broke binary in build stage that terraform needs to init. Your changes for local testing work just that the runner for the action did not like the build stage of the makefile with your changes

**Review by snowmang1 — APPROVED** [review]

**Pull request merged**
